resource_group_name      = "rg-terraform-web"
resource_group_location  = "westeurope"
app_service_plan_name    = "appserviceplan"
app_service_name         = "terraform-gekaweb-test2"
vnet_service_name        = "vnet-gateway"
public_ip_service_name   = "gateway-ip" 
app_gateway_service_name = "app-gateway"
domain_name              = "gekaappgatawey"