---
AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation Nested PostgresqlRDS Stack

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup for PostgresqlDB
      DBSubnetGroupName: DBSubnetGroup
      SubnetIds:
        - !ImportValue PrivateA
        - !ImportValue PrivateB
      Tags:
      - Key: Name
        Value:
          !Join
          - ''
          - - 'db-subnet-group-'
            - !Ref 'AWS::StackName'


  PostgresqlRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      AvailabilityZone: !Select [ 0, "Fn::GetAZs": { Ref: "AWS::Region" } ]
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: postgres
      EngineVersion: 10.19
      MasterUsername: fa
      MasterUserPassword: password123
      MultiAZ: 'false'
      Port: 5432
      PubliclyAccessible: 'false'
      StorageType: gp2
      VPCSecurityGroups:
        - !ImportValue SecurityGroupID
      Tags:
      - Key: Name
        Value:
          !Join
          - ''
          - - 'postgres-rds-'
            - !Ref 'AWS::StackName'
