---
- hosts: all
  become: true
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Install mysql-server
      apt:
        name: mysql-server
        state: latest

    - name: Install mysql-client
      apt:
        name: mysql-client
        state: latest

    - name: Install java
      apt:
        name: default-jdk
        state: latest
        install_recommends: no

    - name: download tomcat server packages
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.16/bin/apache-tomcat-10.0.16.tar.gz
        dest: /usr/local

    - name: extract tomcat packages
      unarchive:
        src: /usr/local/apache-tomcat-10.0.16.tar.gz
        dest: /usr/local
        remote_src: yes

    - name: start tomcat services
      shell: nohup /usr/local/apache-tomcat-10.0.16/bin/startup.sh
